# Generated by Django 5.2 on 2025-08-01 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_feed_price_userfeedrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='是否審核通過（需要5人確認）'),
        ),
        migrations.AddField(
            model_name='feed',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='已審核人數'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='飼料價格', max_digits=10),
        ),
        migrations.CreateModel(
            name='FeedErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('name', '名稱錯誤'), ('brand', '品牌錯誤'), ('nutrition', '營養成分錯誤'), ('price', '價格錯誤'), ('image', '圖片錯誤'), ('other', '其他錯誤')], help_text='錯誤類型', max_length=20)),
                ('description', models.TextField(help_text='錯誤描述')),
                ('is_resolved', models.BooleanField(default=False, help_text='是否已處理')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='feeds.feed')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_error_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['feed', 'is_resolved'], name='feeds_feede_feed_id_349f13_idx'), models.Index(fields=['reporter', 'reported_at'], name='feeds_feede_reporte_f3e41e_idx'), models.Index(fields=['error_type'], name='feeds_feede_error_t_bc129c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='feeds.feed')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['feed', 'reviewer'], name='feeds_feedr_feed_id_810c4e_idx'), models.Index(fields=['reviewed_at'], name='feeds_feedr_reviewe_7a2f0f_idx')],
                'unique_together': {('feed', 'reviewer')},
            },
        ),
    ]
